開発環境ガイド新規作成
solxyz-jsn/solxyz-development-standard pull request #11
Opened 2023-09-08 02:49 UTC by mnmn0

次のドキュメントを新規追加

- Giteaセットアップ方法
- SonarQubeセットアップ方法
- Gitea使用方法
- SonarQube使用方法
- CI/CDに関する情報

関連Issue
https://github.com/solxyz-jsn/solxyz-development-standard/issues/10

2023-09-08 05:08 UTC, kouohara-solx requested changes
全体的に前提知識がないひとにやさしくない印象です。
前提文書があるのであれば、引用したいです。

2023-09-08 05:08 UTC, kouohara-solx commented on development-environment-structure/gitea/gitea-setup.md
> +サイドバーから`ユーザーアカウント`を選択し、`ユーザーアカウントの作成`からユーザーを作成します。
作成されるとどうなる？
ユーザーにメールが飛ぶとか？

2023-09-08 05:08 UTC, kouohara-solx commented on development-environment-structure/gitea/gitea-setup.md
> +.gitignoreはテンプレートに用意されていないものもあります。その場合は、自分で作成する必要があります。
テンプレートが突然出てきます。

2023-09-08 05:08 UTC, kouohara-solx commented on development-environment-structure/gitea/gitea-setup.md
> +![Alt text](./images/act-2.png)
画像、あってますか？
見せたいところがどこかわかるようにした方がよいです。
左のメニューのランナー？

2023-09-08 05:08 UTC, kouohara-solx commented on development-environment-structure/gitea/gitea-setup.md
> +Actionsのランナーを選択します。
ランナーとは？

2023-09-08 05:08 UTC, kouohara-solx commented on development-environment-structure/gitea/gitea-setup.md
> +コピーしたTokenを配布したK8sのリソースファイル`gitea-act-runner.yaml`の`token`に設定します。
どこのディレクトリにある？

2023-09-08 05:08 UTC, kouohara-solx commented on development-environment-structure/gitea/gitea-setup.md
> +このテンプレートは、別途解説します。
このテンプレートとは？
Gitea Actionsのテンプレートは・・・とか？

2023-09-08 07:50 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +永続ボリュームは、Podが削除されてもデータが消えないようにするために必要です。
OSセットアップガイドにK8sに関するドキュメントは記載しております。
OSセットアップでは、K8sのインストールを行うため、全ての説明をまとめています。

2023-09-08 07:50 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +Giteaのインストールは、K8s上にデブロイします。
GitHub上ではファイルの並びが見づらいかと思いますが、index.mdに全て記載してあります。
index.mdから遷移できるように目次のリンクを追加しました。
目次を作る過程で、OSセットアップに関するファイルを一つ上の階層に移動しました。

2023-09-08 07:54 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +Giteaの管理者ユーザーを作成します。
以下の文を追加しました。

> Giteaの管理者ユーザーを作成します。Giteaの管理者ユーザーとは、このホスティングされたGiteaのすべての設定を変更できるユーザーです。管理者ユーザーは、リポジトリの管理者とは異なります。

2023-09-13 01:20 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +![Alt text](./images/act-2.png)
赤枠追加しました。

2023-09-13 01:54 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +Actionsのランナーを選択します。
ランナーの説明を追加しました。

> ランナーとは、Gitea Actionsのジョブを実行するための仮想マシンです。

2023-09-13 02:00 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +コピーしたTokenを配布したK8sのリソースファイル`gitea-act-runner.yaml`の`token`に設定します。
このディレクトリは、他のSonarQubeにも関わるものなので、index.mdのファイルに追記しました。

2023-09-13 04:41 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +サイドバーから`ユーザーアカウント`を選択し、`ユーザーアカウントの作成`からユーザーを作成します。
メールサーバあれば、作られたユーザー側への通知が送信されます。
今回はクローズドネットワークで運用することを想定し、メールサーバなどを立てない手軽さをウリにしています。
そのため、そのような通知は送信しません。

次の文面を追加しました。

> このユーザーは、Giteaにログインするためのユーザーです。
>
> ユーザーの登録機能を無効化している場合は、この操作でのみ、ユーザーを作成することができます。

2023-09-14 01:13 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +.gitignoreはテンプレートに用意されていないものもあります。その場合は、自分で作成する必要があります。
加筆しました

2023-09-14 02:06 UTC, mnmn0 commented on development-environment-structure/gitea/gitea-setup.md
> +このテンプレートは、別途解説します。
リンクを追加しました

2023-09-14 02:10 UTC, kouohara-solx approved these changes

2023-09-15 08:39 UTC, rykomatsu-t approved these changes

2023-09-15 08:39 UTC, rykomatsu-t commented on development-environment-structure/index.md
> +Gitの基本的な使い方については、ソルクシーズアカデミーを参照してください。
```suggestion
Gitの基本的な使い方については、[ソルクシーズアカデミー](https://academy.solxyz.co.jp/developers/git-basic/list)を参照してください。
```

2023-09-15 08:39 UTC, rykomatsu-t commented on development-environment-structure/gitea/gitea-setup.md
> +![Alt text](./images/organization-detail.png)
```suggestion
![組織詳細画面](./images/organization-detail.png)
```

2023-09-15 08:39 UTC, rykomatsu-t commented on development-environment-structure/gitea/gitea-setup.md
> +![Alt text](./images/admin-user-management.png)
```suggestion
![ユーザー管理画面](./images/admin-user-management.png)
```

2023-09-15 08:39 UTC, rykomatsu-t commented on development-environment-structure/gitea/github_flow.md
> +CIは、プルリクエストがオープンな時、pushされた際に自動で実行されます。
```suggestion
CIは、プルリクエストがオープンな時、pushをトリガーとして自動で実行されます。
```

2023-09-15 08:39 UTC, rykomatsu-t commented on development-environment-structure/how-to-use-ci-cd.md
> +Javaであれば、MavenやGradle、Node.jsであればnpmやyarnなどです。
```suggestion
JavaであればMavenやGradle、Node.jsであればnpmやyarnなどです。
```

2023-09-17 12:21 UTC, mnmn0 commented on development-environment-structure/index.md
> +Gitの基本的な使い方については、ソルクシーズアカデミーを参照してください。
全体に公開するものなのでURLは過剰かなと

2023-09-19 00:55 UTC, merged